import type { Book, ExchangeHistory, User } from './types';

export const INITIAL_USERS: User[] = [
  { id: 'user-1', name: 'Иван Петров', email: 'ivan@example.com' },
  { id: 'user-2', name: 'Анна Сидорова', email: 'anna@example.com' },
  { id: 'user-3', name: 'Сергей Смирнов', email: 'sergey@example.com' },
];

export const INITIAL_BOOKS: Book[] = [
  {
    id: 'book-1',
    title: 'Мастер и Маргарита',
    author: 'Михаил Булгаков',
    genre: 'Классика',
    year: 1967,
    description: 'Великий роман о сатане, посетившем Москву 1930-х годов, и трагической любви мастера и Маргариты.',
    condition: 'Отличное',
    ownerId: 'user-1',
    ownerName: 'Иван Петров',
    status: 'Доступна',
    pickupLocation: 'м. Университет / библиотеки МТУСИ',
    createdAt: '2026-09-20',
  },
  {
    id: 'book-2',
    title: '1984',
    author: 'Джордж Оруэлл',
    genre: 'Антиутопия',
    year: 1949,
    description: 'Роман-антиутопия о тоталитарном государстве, контролирующем мысль и поступки каждого человека.',
    condition: 'Хорошее',
    ownerId: 'user-2',
    ownerName: 'Анна Сидорова',
    status: 'Забронирована',
    pickupLocation: 'м. Сокол, парковая зона',
    createdAt: '2026-09-21',
  },
  {
    id: 'book-3',
    title: 'Чистый код',
    author: 'Роберт Мартин',
    genre: 'Программирование',
    year: 2008,
    description: 'Создание, анализ и рефакторинг. Практическое руководство по написанию качественного кода.',
    condition: 'Новое',
    ownerId: 'user-1',
    ownerName: 'Иван Петров',
    status: 'Доступна',
    pickupLocation: 'Главный корпус МТУСИ',
    createdAt: '2026-09-22',
  },
  {
    id: 'book-4',
    title: 'Граф Монте-Кристо',
    author: 'Александр Дюма',
    genre: 'Приключения',
    year: 1844,
    description: 'Захватывающая история о мести, верности, предательстве и великодушии Эдмона Дантеса.',
    condition: 'Зачитанное',
    ownerId: 'user-3',
    ownerName: 'Сергей Смирнов',
    status: 'Выдана',
    pickupLocation: 'м. Таганская',
    createdAt: '2026-09-15',
  },
  {
    id: 'book-5',
    title: 'Гарри Поттер и Философский камень',
    author: 'Дж. К. Роулинг',
    genre: 'Фэнтези',
    year: 1997,
    description: 'Первая книга о приключениях сироты Гарри Поттера, узнавшего в 11 лет, что он волшебник.',
    condition: 'Отличное',
    ownerId: 'user-2',
    ownerName: 'Анна Сидорова',
    status: 'Доступна',
    pickupLocation: 'м. Октябрьское поле',
    createdAt: '2026-09-23',
  },
  {
    id: 'book-6',
    title: 'Искусство программирования. Том 1',
    author: 'Дональд Кнут',
    genre: 'Программирование',
    year: 1968,
    description: 'Фундаментальный труд по алгоритмам и структурам данных.',
    condition: 'Хорошее',
    ownerId: 'user-3',
    ownerName: 'Сергей Смирнов',
    status: 'Возвращена',
    pickupLocation: 'м. Авиамоторная',
    createdAt: '2026-09-10',
  }
];

export const INITIAL_EXCHANGES: ExchangeHistory[] = [
  {
    id: 'ex-1',
    bookId: 'book-2',
    bookTitle: '1984',
    ownerId: 'user-2',
    ownerName: 'Анна Сидорова',
    recipientId: 'user-1',
    recipientName: 'Иван Петров',
    bookingDate: '2026-09-22',
    status: 'Забронирована',
  },
  {
    id: 'ex-2',
    bookId: 'book-4',
    bookTitle: 'Граф Монте-Кристо',
    ownerId: 'user-3',
    ownerName: 'Сергей Смирнов',
    recipientId: 'user-2',
    recipientName: 'Анна Сидорова',
    bookingDate: '2026-09-16',
    status: 'Выдана',
  },
  {
    id: 'ex-3',
    bookId: 'book-6',
    bookTitle: 'Искусство программирования. Том 1',
    ownerId: 'user-3',
    ownerName: 'Сергей Смирнов',
    recipientId: 'user-1',
    recipientName: 'Иван Петров',
    bookingDate: '2026-09-10',
    completionDate: '2026-09-18',
    status: 'Возвращена',
  }
];
